# GENERATED by lfpoop.onionize — the LFPOOPy onion of wordstats
'wordstats — a tiny text-analytics program: THE LFPOOP EXAMPLE SUBJECT.\n\nThis is PLAIN PYTHON. It imports nothing from lfpoop. It is the "other code"\nLFPOOP reads and transforms — the point of the example is that lfpoop takes\nTHIS, that it has never seen, and emits its onion (examples/wordstats_onion.py),\nproven by wordstats\' OWN test suite (examples/test_wordstats.py) running green\nagainst the onionized build.\n\nIt is deliberately shaped to exercise the whole pipeline:\n  * an internal CALL CHAIN (top_words → word_count → tokenize → normalize)\n    so rollup has real wiring to learn;\n  * a CURRIED CONFIG param (`stopwords`, shared across four functions) so\n    classify/apionize have an alphabet to factor;\n  * an AUGASSIGN accumulator (`n += 1`) — the shadow path the v4 verifier\n    found and we fixed;\n  * a LAMBDA inside a statement (the sort key) — sealed as an opaque block;\n  * a CLASS with methods — opened at method grain.\n'

import re

_WORD = re.compile("[a-z']+")

def _normalize_blk_0(text):
    return text.lower().strip()
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})

def normalize(text):
    _r = _normalize_blk_0(text=text)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    return None

def _tokenize_blk_0(text):
    norm = normalize(text)
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('norm',) if w in _loc})

def _tokenize_blk_1(norm):
    return _WORD.findall(norm)
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})

def tokenize(text):
    _r = _tokenize_blk_0(text=text)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'norm' in _r[1]: norm = _r[1]['norm']
    _r = _tokenize_blk_1(norm=norm)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    return None

def _word_count_blk_0():
    counts = {}
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('counts',) if w in _loc})

def _word_count_blk_1(counts, stopwords, text):
    for tok in tokenize(text):
        if tok in stopwords:
            continue
        counts[tok] = counts.get(tok, 0) + 1
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('tok',) if w in _loc})

def _word_count_blk_2(counts):
    return counts
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})

def word_count(text, stopwords):
    _r = _word_count_blk_0()
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'counts' in _r[1]: counts = _r[1]['counts']
    _r = _word_count_blk_1(counts=counts, stopwords=stopwords, text=text)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'tok' in _r[1]: tok = _r[1]['tok']
    _r = _word_count_blk_2(counts=counts)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    return None

def _total_words_blk_0():
    n = 0
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('n',) if w in _loc})

def _total_words_blk_1(n, stopwords, text):
    for tok in tokenize(text):
        if tok not in stopwords:
            n += 1
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('n', 'tok') if w in _loc})

def _total_words_blk_2(n):
    return n
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})

def total_words(text, stopwords):
    _r = _total_words_blk_0()
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'n' in _r[1]: n = _r[1]['n']
    _r = _total_words_blk_1(n=n, stopwords=stopwords, text=text)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'n' in _r[1]: n = _r[1]['n']
    if 'tok' in _r[1]: tok = _r[1]['tok']
    _r = _total_words_blk_2(n=n)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    return None

def _top_words_blk_0(stopwords, text):
    counts = word_count(text, stopwords)
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('counts',) if w in _loc})

def _top_words_blk_1(counts):
    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('ranked',) if w in _loc})

def _top_words_blk_2(k, ranked):
    return ranked[:k]
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})

def top_words(text, stopwords, k):
    _r = _top_words_blk_0(stopwords=stopwords, text=text)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'counts' in _r[1]: counts = _r[1]['counts']
    _r = _top_words_blk_1(counts=counts)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    if 'ranked' in _r[1]: ranked = _r[1]['ranked']
    _r = _top_words_blk_2(k=k, ranked=ranked)
    if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
        return _r
    return None

def _Report___init___blk_0(self, stopwords):
    self.stopwords = stopwords
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})
def _Report_summary_blk_0(self, text):
    total = total_words(text, self.stopwords)
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('total',) if w in _loc})
def _Report_summary_blk_1(k, self, text):
    top = top_words(text, self.stopwords, k)
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in ('top',) if w in _loc})
def _Report_summary_blk_2(top, total):
    return {'total': total, 'top': top}
    _loc = locals()
    return ('__w__', {w: _loc[w] for w in () if w in _loc})
class Report:
    'A stateful reporter — its stopwords are its bound configuration.'
    def __init__(self, stopwords):
        _r = _Report___init___blk_0(self=self, stopwords=stopwords)
        if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
            return _r
        return None
    def summary(self, text, k):
        _r = _Report_summary_blk_0(self=self, text=text)
        if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
            return _r
        if 'total' in _r[1]: total = _r[1]['total']
        _r = _Report_summary_blk_1(k=k, self=self, text=text)
        if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
            return _r
        if 'top' in _r[1]: top = _r[1]['top']
        _r = _Report_summary_blk_2(top=top, total=total)
        if not (isinstance(_r, tuple) and len(_r) == 2 and _r[0] == '__w__'):
            return _r
        return None

# THE LEARNED ROLL-UP — rings from the module's own wiring
class Ring_tokenize:
    __ring_members__ = ['normalize', 'tokenize', 'top_words', 'total_words', 'word_count']
    normalize = staticmethod(normalize)
    tokenize = staticmethod(tokenize)
    top_words = staticmethod(top_words)
    total_words = staticmethod(total_words)
    word_count = staticmethod(word_count)

class WordstatsOnion:
    __function_rings__ = ['Ring_tokenize']
    __class_rings__ = ['Report']
    __rings__ = ['Ring_tokenize', 'Report']
