"""classify — CLASS-IFY: turn a curried function into a CLASS (the real ②).

The word is the spec: to classify a curried function is to MAKE IT A CLASS.
Partial application, reified:

    CONSTRUCTION = binding the CURRIED alphabet (the config slots) —
                   monotone, one substitution per bind(), soup until the
                   LFP of substitutions closes (heat = unbound count);
    THE CALL     = applying the RESIDUE (the per-call parameters that
                   stayed free) — refused BY NAME while any slot is open;
    THE CLASS    = the curried function as a first-class, stateful,
                   composable, data-carrying object: __curried__,
                   __residue__, __impl__ ride the class as metadata, so
                   the class-ified form is queryable ontology like
                   everything else.

This is what the whole pipeline was building toward: blocks functionalizes
(statement → function of its frees), the curry decider (alphabets.py) says
WHICH frees are config, and classify turns the curried result into the
class — the unit the onion rolls up base→meta→super. apionize is the
group case (many callables sharing one curried alphabet → one class, many
residue methods); class_ify_group re-expresses it as CODE OUT.

Everything here EMITS SOURCE (code out, per the thesis) and then compiles
it; the shadow law applies: the class-ified form must behave identically
to direct application of the original.

Stdlib + lfpoop.alphabets.
"""
import ast
import textwrap

from .alphabets import curry_plan


class ClassifyRefusal(ValueError):
    """A function this transformer cannot honestly class-ify — named."""


def _fn_info(source):
    tree = ast.parse(textwrap.dedent(source))
    fdef = tree.body[0]
    if not isinstance(fdef, ast.FunctionDef):
        raise ClassifyRefusal("input must be a single function def")
    params = [a.arg for a in fdef.args.args]
    defaults = {}
    for a, d in zip(reversed(fdef.args.args),
                    reversed(fdef.args.defaults)):
        defaults[a.arg] = ast.unparse(d)
    return fdef.name, params, defaults


def class_ify(source, slots=None, context=None, class_name=None):
    """ONE curried function → ONE class, as SOURCE (code out).

    slots: the curried alphabet (which params become construction-bound
    state). If omitted, the curry decider chooses (config-classified
    params). The residue = the remaining params = the call surface.
    Returns (class_source, meta)."""
    name, params, defaults = _fn_info(source)
    if slots is None:
        slots = curry_plan(source, context)["slots"]
    slots = [s for s in params if s in set(slots)]      # signature order
    residue = [p for p in params if p not in slots]
    if not slots:
        raise ClassifyRefusal(
            f"{name}: nothing curries — no config alphabet among params "
            f"{params}; a class with no bound state is just the function")
    cname = class_name or name.title().replace("_", "")
    res_sig = ", ".join(f"{p}={defaults[p]}" if p in defaults else p
                        for p in residue)
    res_pass = ", ".join(f"{p}={p}" for p in residue)
    slot_pass = ", ".join(f"{s}=self._bound['{s}']" for s in slots)
    lines = [
        f"# GENERATED by lfpoop.classify — {name}, class-ified",
        f"# curried: {slots}  residue: {residue}",
        textwrap.dedent(source).strip().replace(
            f"def {name}(", f"def _impl_{name}(", 1),
        "",
        f"class {cname}:",
        f"    __curried__ = {tuple(slots)!r}",
        f"    __residue__ = {tuple(residue)!r}",
        f"    __impl__ = {name!r}",
        f"    def __init__(self, **bindings):",
        f"        self._bound = {{}}",
        f"        for k, v in bindings.items():",
        f"            self.bind(k, v)",
        f"    def bind(self, slot, value):",
        f"        if slot not in self.__curried__:",
        f"            raise KeyError(",
        f"                f'{{slot!r}} is not in the curried alphabet '",
        f"                f'{{self.__curried__}} (residue goes to the call)')",
        f"        if slot in self._bound:",
        f"            raise ValueError(",
        f"                f'slot {{slot!r}} already bound — substitutions '",
        f"                f'are monotone; make a new instance to rebind')",
        f"        self._bound[slot] = value",
        f"        return self",
        f"    @property",
        f"    def heat(self):",
        f"        return len(self.__curried__) - len(self._bound)",
        f"    @property",
        f"    def soup(self):",
        f"        return [s for s in self.__curried__",
        f"                if s not in self._bound]",
        f"    def __call__(self, {res_sig}):" if residue else
        f"    def __call__(self):",
        f"        if self.soup:",
        f"            raise RuntimeError(",
        f"                f'{cname} is SOUP: unbound slots {{self.soup}} — '",
        f"                f'bind() them; the call activates at the LFP '",
        f"                f'of substitutions')",
        f"        return _impl_{name}({slot_pass}"
        + (f", {res_pass})" if residue else ")"),
    ]
    class_source = "\n".join(lines) + "\n"
    return class_source, {"name": name, "class_name": cname,
                          "curried": slots, "residue": residue}


def compile_class(class_source, meta, globals_ns=None):
    ns = dict(globals_ns or {})
    exec(class_source, ns)
    return ns[meta["class_name"]]


def class_ify_group(name, sources, slots, class_name=None):
    """The GROUP case (apionize, as CODE OUT): many functions sharing one
    curried alphabet → ONE class whose state is the shared slots and whose
    METHODS are the residues. Returns (class_source, meta)."""
    cname = class_name or name.title().replace("_", "")
    infos = [_fn_info(src) for src in sources]
    lines = [f"# GENERATED by lfpoop.classify — group class {cname}",
             f"# shared curried alphabet: {sorted(slots)}"]
    for src, (fname, _, _) in zip(sources, infos):
        lines.append(textwrap.dedent(src).strip().replace(
            f"def {fname}(", f"def _impl_{fname}(", 1))
        lines.append("")
    lines += [
        f"class {cname}:",
        f"    __curried__ = {tuple(sorted(slots))!r}",
        f"    def __init__(self, **bindings):",
        f"        self._bound = {{}}",
        f"        for k, v in bindings.items():",
        f"            if k not in self.__curried__:",
        f"                raise KeyError(f'{{k!r}} not in the curried "
        f"alphabet')",
        f"            self._bound[k] = v",
        f"    @property",
        f"    def soup(self):",
        f"        return [s for s in self.__curried__",
        f"                if s not in self._bound]",
    ]
    methods = {}
    for src, (fname, params, defaults) in zip(sources, infos):
        f_slots = [p for p in params if p in set(slots)]
        f_res = [p for p in params if p not in set(slots)]
        methods[fname] = {"curried": f_slots, "residue": f_res}
        res_sig = ", ".join(f"{p}={defaults[p]}" if p in defaults else p
                            for p in f_res)
        call_args = ", ".join(
            [f"{s}=self._bound['{s}']" for s in f_slots]
            + [f"{p}={p}" for p in f_res])
        lines += [
            f"    def {fname}(self, {res_sig})"
            f":" if f_res else f"    def {fname}(self):",
            f"        missing = [s for s in {tuple(f_slots)!r}",
            f"                   if s not in self._bound]",
            f"        if missing:",
            f"            raise RuntimeError(",
            f"                f'{fname} is SOUP: unbound {{missing}}')",
            f"        return _impl_{fname}({call_args})",
        ]
    class_source = "\n".join(lines) + "\n"
    return class_source, {"class_name": cname, "methods": methods,
                          "curried": sorted(slots)}
